### ISSUE TITLE
Bad file descriptor

### ISSUE THREAD

**Issue by gfrankliu** [weibocom/nginx-upsync-module#94]
Has anybody seen this error in the nginx error log?

```
2016/07/22 03:38:01 [emerg] 19440#19440: close() "/tmp/upstream.tmp" failed (9: Bad file descriptor)
```

upsync_dump_path /tmp/upstream.tmp;

**Comment by gfrankliu** [comment]
My nginx error has bunch of those every time when I do log rotation with kill -USR1

**Comment by xiaokai-wang** [comment]
Is that impact the normal work? That's strange.

Why do you use 'kill' to do log rotation? I am sorry, what dose '-USR1' mean?

**Comment by gfrankliu** [comment]
https://www.nginx.com/resources/wiki/start/topics/examples/logrotation/

**Comment by xiaokai-wang** [comment]
Fresh me, thanks.

**Comment by xiaokai-wang** [comment]
When you send '-USR1' to nginx.master which will reopen all file with attribute 'APPEND', of course that doesn't suit to upsync-dump-file . So I will reopen the file when changes happen and then close it. 

You did log rotation every night, error happened every time? I think it is not a perfect method, why not use shell?

**Comment by gfrankliu** [comment]
I think it is a better idea to open/close the dump file as needed, than keeping it open all the time. If you really want to keep it open all the time, we probably should not use the APPEND attribute because the file operation is most likely not just APPEND.

By the way, will there any compete (race condition) from different thread to update this file?

I don't know what you mean by "why not use shell". I think the USR1 signal is the best option. If you have a busy site with big access log file, you probably need to rotate the file several times an hour, so you can compress/archive the old files. In order to provide undisrupted traffic during log rotation, the USR1 signal was provided by nginx.

**Comment by xiaokai-wang** [comment]
The dump file has been realized to be opened/closed as needed with a mutex lock for race condition.

Yeah, please ignore what I said. That's maybe the best option to do log rotation. Thanks.

Back to the question, I think the error should not be happened every time, confused.

**Comment by gfrankliu** [comment]
I have 5 "upstream" definition and each one uses a different dump file. Each time rotation happens, I see 10 of those errors in the error log: 2 per dump file.
You can test it by sudo kill -USR1 <master_pid> and you will see 2 such errors in the error log if you have a single "upstream" with single dump file.

**Comment by xiaokai-wang** [comment]
The bug was fixed, pleas update and have a try.

**Comment by gfrankliu** [comment]
It works. Error message is gone.

**Comment by mrBob90** [comment]
is this bug fixed for branch nginx-upsync-1.8.x ,we  allow use 'kill -USR1' to do log rotation, i find this problem is still unsolved,'Bad file descriptor' is still in nginx error log.
